In [1]:
import os
print(os.getcwd())
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

'/home/sepidehparhami/tutoring/Research Project'

In [51]:
yields = pd.read_csv(r'yield.txt', delim_whitespace=True, index_col=0)

In [52]:
ligands = list(yields.index)
ligands

['L01',
 'L02',
 'L04',
 'L05',
 'L06',
 'L07',
 'L08',
 'L12',
 'L15',
 'L16',
 'L17',
 'L18',
 'L20',
 'L21',
 'L22',
 'L23',
 'L24',
 'L25',
 'L26',
 'L27',
 'L28',
 'L29',
 'L30',
 'L33',
 'L34',
 'L35',
 'L36',
 'TL01',
 'TL02',
 'TL03',
 'TL04',
 'TL05',
 'TL06',
 'TL07',
 'TL08',
 'TL09',
 'TL11',
 'TL12',
 'TL13']

In [53]:
np.array(yields)

array([[83.3,  8.9,  7.9],
       [70.8, 18.4, 10.8],
       [68.9, 17.6, 13.5],
       [75.4, 24.4,  0.2],
       [44.1, 42.3, 13.5],
       [32.2, 59. ,  8.8],
       [ 9.8, 90. ,  0.1],
       [16. , 74.8,  9.1],
       [24. , 53. , 23. ],
       [10. , 16.5, 73.5],
       [12.5, 30.2, 57.3],
       [16.5, 40.7, 42.8],
       [20.4, 49.3, 30.4],
       [44.3, 75.1, 13.5],
       [32.5, 67.4,  0.1],
       [ 0.1, 99.8,  0.1],
       [ 0.1, 99.8,  0.1],
       [ 9.4, 54.1, 36.5],
       [12.2, 46.8, 41. ],
       [ 7. , 92.2,  0.1],
       [22.8, 77.1,  0.1],
       [11.5, 68.4, 20.1],
       [14.6, 67.1, 18.3],
       [46. , 37.4, 16.6],
       [24.1, 59.4, 16.4],
       [51.9, 33. , 15.1],
       [54. , 24.4, 21.6],
       [24.5, 69.8,  5.7],
       [28.7, 64.4,  6.9],
       [18.8, 74.5,  6.7],
       [25.7, 65.6,  8.7],
       [18.2, 75.1,  6.7],
       [20.6, 73.8,  5.6],
       [16.2, 79.5,  4.3],
       [30. , 64.2,  5.8],
       [16.6, 77.2,  6.2],
       [18.9, 77.2,  3.9],
 

In [4]:
# to map all three to a ligand
#yield_dict = yields.set_index('Ligand').T.to_dict('list')

#Create a map of ligands to their yield ratios
#has the form: {"ligand name" : [yield value] } 
# note that the value will be in an array, so it has to be accessed by 
# yields.columns= ['Ligand', '3', '4', '5']
# yield_dict = yields[['Ligand', '3']].set_index('Ligand').T.to_dict('list')

#to map ligand to 4
#yield_dict = yields['Ligand', '4'].set_index('Ligand').T.to_dict('list')

#to map ligand to 5
#yield_dict = yields['Ligand', '5'].set_index('Ligand').T.to_dict('list')


In [54]:
n_molecules = yields.shape[0]
n_coords = 26999

In [59]:
n_molecules

39

In [56]:
# initialize a data frame and fill in ESPs from file
# later we will save the (x,y,z) coordinates too to make use of them
data = pd.DataFrame(index = ligands, columns=range(n_coords))


directory = './data' 
      
#loop through files in directory
for filename in os.listdir(directory):
    data_point = pd.read_csv('./data/{}'.format(filename))
    data_point.columns = ('x', 'y', 'z', 'esp')
    name_parts = filename.split("_")

        
    #extract the ligand name from the filename
    if name_parts[1][0] == "T":
        ligand = name_parts[1][:4]
    else:
        ligand = name_parts[1][:3]
        
    #add label and data point to their respective arrays 
    data.loc[ligand] = data_point['esp']

In [57]:
data

0     1     2     3     4     5     6     7     8     9      ... 26989  \
L01    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L02    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L04    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L05    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L06    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L07    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L08    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L12    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L15    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L16    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L17    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L18    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L20    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L21    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L22    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L23    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L24    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L25    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L26    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L27    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L28    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L29    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L30    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L33    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L34    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L35    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L36    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
TL01   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
TL02   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
TL03   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
TL04   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
TL05   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
TL06   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
TL07   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
TL08   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
TL09   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
TL11   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
TL12   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
TL13   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

     26990 26991 26992 26993 26994 26995 26996 26997 26998  
L01    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L02    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L04    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L05    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L06    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L07    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L08    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L12    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L15    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L16    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L17    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L18    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L20    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.

In [62]:
#split into train and test sets
x_train, x_test, y_train, y_test = train_test_split(data, yields, test_size=0.2, random_state=42, shuffle=True)

In [77]:
x_train.head()

0     1     2     3     4     5     6     7     8     9      ... 26989  \
L34   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L23   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L25   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L15   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
L24   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

    26990 26991 26992 26993 26994 26995 26996 26997 26998  
L34   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L23   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L25   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L15   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
L24   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 26999 columns]

In [78]:
y_train

3     4     5
Ligand                  
L34     24.1  59.4  16.4
L23      0.1  99.8   0.1
L25      9.4  54.1  36.5
L15     24.0  53.0  23.0
L24      0.1  99.8   0.1
L20     20.4  49.3  30.4
L27      7.0  92.2   0.1
L16     10.0  16.5  73.5
TL06    20.6  73.8   5.6
L01     83.3   8.9   7.9
L35     51.9  33.0  15.1
L07     32.2  59.0   8.8
L18     16.5  40.7  42.8
L02     70.8  18.4  10.8
TL12    59.4  28.9  11.7
L29     11.5  68.4  20.1
L04     68.9  17.6  13.5
TL03    18.8  74.5   6.7
TL09    16.6  77.2   6.2
L05     75.4  24.4   0.2
TL08    30.0  64.2   5.8
L33     46.0  37.4  16.6
TL05    18.2  75.1   6.7
L17     12.5  30.2  57.3
L30     14.6  67.1  18.3
L26     12.2  46.8  41.0
L28     22.8  77.1   0.1
L12     16.0  74.8   9.1
L22     32.5  67.4   0.1
TL02    28.7  64.4   6.9
TL13    28.5  62.9   8.7

In [79]:
y_test

3     4     5
Ligand                  
TL07    16.2  79.5   4.3
TL11    18.9  77.2   3.9
L06     44.1  42.3  13.5
L21     44.3  75.1  13.5
TL04    25.7  65.6   8.7
L36     54.0  24.4  21.6
L08      9.8  90.0   0.1
TL01    24.5  69.8   5.7

In [83]:
#create and fit linear regression model
LR = LinearRegression()
LR.fit(x_train, y_train)
y_prediction =  LR.predict(x_test)

In [89]:
print('MSE:', mean_squared_error(y_test, y_prediction))
print('R^2:', r2_score(y_test, y_prediction))

MSE: 290.19973967121626
R^2: -0.9185016644454862


In [ ]:
y_prediction.to_csv("./predicted.csv")
print ("Loss from linear regression:") 
print (log_loss(y_prediction, np.array(y_test))

In [68]:
y_prediction

array([[29.6007929 , 52.3685711 , 18.03923458],
       [29.70710214, 51.84722603, 18.46355237],
       [29.38918661, 44.06778104, 26.47119499],
       [29.1775519 , 53.07194387, 17.76317982],
       [29.42206302, 59.52505013, 11.10344102],
       [29.32157033, 52.98701065, 17.70288724],
       [23.18877175, 55.4016806 , 21.39345622],
       [28.98160021, 53.22883115, 17.80070407]])

In [70]:
np.array(y_test)

array([[16.2, 79.5,  4.3],
       [18.9, 77.2,  3.9],
       [44.1, 42.3, 13.5],
       [44.3, 75.1, 13.5],
       [25.7, 65.6,  8.7],
       [54. , 24.4, 21.6],
       [ 9.8, 90. ,  0.1],
       [24.5, 69.8,  5.7]])